### ISSUE TITLE
Docker-compose issue with database

### ISSUE THREAD

**Issue by Ewa-Anna** [Ewa-Anna/Bookstore#38]
While running app in Docker Compose, the database after each run is being deleted (nothing is stored).
1) Connect to existing PostgreSQL database on local machine
or
2) Create lasting PostgreSQL database in docker contener

**Comment by Ewa-Anna** [comment]
Updated docker-compose.yml file with:
```
db:
    #...
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
```
